version: '3.9'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    volumes:
      - wordpress_data:/var/lib/wordpress/
    ports:
      - '${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}'
    restart: always
    networks:
      - 'ltheresi-inception'

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb-container
    ports:
      - '${MARIADB_HOST_PORT}:${MARIADB_CONTAINER_PORT}'
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - 'ltheresi-inception'

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/lib/wordpress
    container_name: wordpress-container
    restart: always
    networks:
      - 'ltheresi-inception'

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp-container
    ports:
      - '${FTP_20_HOST}:${FTP_20_CONTAINER}'
      - '${FTP_21_HOST}:${FTP_21_CONTAINER}'
      - '${FTP_21000_HOST}:${FTP_21000_CONTAINER}'
    volumes:
      - wordpress_data:/home/ltheresi/
    restart: always
    networks:
      - 'ltheresi-inception'

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis-container
    restart: always
    networks:
      - 'ltheresi-inception'

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer-container
    restart: always
    networks:
      - 'ltheresi-inception'

  influx:
    build:
      context: ./requirements/bonus/influx
      dockerfile: Dockerfile
    container_name: influx-container
    restart: always
    networks:
      - 'ltheresi-inception'

  grafana:
    build:
      context: ./requirements/bonus/grafana
      dockerfile: Dockerfile
    container_name: grafana-container
    ports:
      - '${GRAFANA_HOST_PORT}:${GRAFANA_CONTAINER_PORT}'
    restart: always
    networks:
      - 'ltheresi-inception'

  telegraf:
    build:
      context: ./requirements/bonus/telegraf
      dockerfile: Dockerfile
    container_name: telegraf-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - 'ltheresi-inception'

  python-cgi:
    build:
      context: ./requirements/bonus/pythonCGI
      dockerfile: Dockerfile
    container_name: pythonCGI-container
    ports:
      - '${PYTHON_CGI_HOST_PORT}:${PYTHON_CGI_CONTAINER_PORT}'
    restart: always
    networks:
      - 'ltheresi-inception'

networks:
  ltheresi-inception:
    driver: bridge

volumes:
  mariadb_data:

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /${START_DIR}/${SCHOOL_USER}/data/wordpress_data